/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package form.ppn;

import controller.Controller;
import domain.Nastavnik;
import domain.PlanPokrivenostiNastave;
import domain.StavkaPPN;
import form.FormMode;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import model.PlanoviTableModel;
import model.TableStavkeModel;
import session.Session;
import slucajkoriscenja.SlucajKoriscenja;
import validator.Validator;

/**
 *
 * @author jelena
 */
public class FormPretraziPPN extends javax.swing.JFrame {

    /**
     * Creates new form FormPrikaziPPN
     */
    public FormPretraziPPN() {
        initComponents();
        Nastavnik ulogovan = Session.getInstance().getUlogovan();
        jLblUlogovan.setText(ulogovan.toString());
        setTitle("Planovi pokrivenosti nastave");
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        popuniTabeluPPN();
        popuniTabeluStavke();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLblUlogovan = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPlanovi = new javax.swing.JTable();
        btnPrikaziStavke = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblStavkePPN = new javax.swing.JTable();
        btnIzmeniPPN = new javax.swing.JButton();
        btnPrikaziPPN = new javax.swing.JButton();
        btnObrisiPPN = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Nastavnik"));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLblUlogovan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLblUlogovan, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Planovi pokrivenosti"));

        tblPlanovi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tblPlanovi);

        btnPrikaziStavke.setText("Prikazi stavke");
        btnPrikaziStavke.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrikaziStavkeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 562, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnPrikaziStavke, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnPrikaziStavke)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Stavke"));

        tblStavkePPN.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(tblStavkePPN);

        btnIzmeniPPN.setText("Izmeni PPN");
        btnIzmeniPPN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIzmeniPPNActionPerformed(evt);
            }
        });

        btnPrikaziPPN.setText("Prikazi PPN");
        btnPrikaziPPN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrikaziPPNActionPerformed(evt);
            }
        });

        btnObrisiPPN.setText("Obrisi PPN");
        btnObrisiPPN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnObrisiPPNActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 562, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnObrisiPPN, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnIzmeniPPN, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnPrikaziPPN, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnIzmeniPPN)
                    .addComponent(btnPrikaziPPN)
                    .addComponent(btnObrisiPPN))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPrikaziPPNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrikaziPPNActionPerformed
        int row = tblPlanovi.getSelectedRow();
        if (Validator.getInstance().izabranRed(row)) {
            PlanoviTableModel model = (PlanoviTableModel) tblPlanovi.getModel();
            PlanPokrivenostiNastave ppn = model.getPlan(row);
            Session.getInstance().setTrenutniSlucajKoriscenja(SlucajKoriscenja.SK_PRIKAZI_PPN);
            Session.getInstance().getParametriSK().clear();
            Session.getInstance().getParametriSK().put("ppn", ppn);
            JDialog ppnDialog = new DialogNoviPPN(this, true, FormMode.PRIKAZI);
            ppnDialog.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(this, "Izaberite plan.");
        }
    }//GEN-LAST:event_btnPrikaziPPNActionPerformed

    private void btnIzmeniPPNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIzmeniPPNActionPerformed
        int row = tblPlanovi.getSelectedRow();
        if (Validator.getInstance().izabranRed(row)) {
            PlanoviTableModel model = (PlanoviTableModel) tblPlanovi.getModel();
            PlanPokrivenostiNastave ppn = model.getPlan(row);
            Session.getInstance().setTrenutniSlucajKoriscenja(SlucajKoriscenja.SK_IZMENI_PPN);
            Session.getInstance().getParametriSK().clear();
            Session.getInstance().getParametriSK().put("ppn", ppn);
            JDialog ppnDialog = new DialogNoviPPN(this, true, FormMode.IZMENI);
            ppnDialog.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(this, "Izaberite plan.");
        }
    }//GEN-LAST:event_btnIzmeniPPNActionPerformed

    private void btnPrikaziStavkeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrikaziStavkeActionPerformed
        int row = tblPlanovi.getSelectedRow();
        if (Validator.getInstance().izabranRed(row)) {
            PlanoviTableModel modelPlanovi = (PlanoviTableModel) tblPlanovi.getModel();
            PlanPokrivenostiNastave izabran = modelPlanovi.getPlan(row);
            try {
                List<StavkaPPN> stavkeZaPlan = Controller.getInstance().getAllStavke(izabran.getPpnId());
                TableStavkeModel modelStavke = (TableStavkeModel) tblStavkePPN.getModel();
                modelStavke.setData(stavkeZaPlan);
            } catch (Exception ex) {
                Logger.getLogger(FormPretraziPPN.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Izaberite plan.");
        }
    }//GEN-LAST:event_btnPrikaziStavkeActionPerformed

    private void btnObrisiPPNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnObrisiPPNActionPerformed
        int row = tblPlanovi.getSelectedRow();
        if (Validator.getInstance().izabranRed(row)) {
            try {
                PlanoviTableModel model = (PlanoviTableModel) tblPlanovi.getModel();
                PlanPokrivenostiNastave ppn = model.getPlan(row);
                Session.getInstance().setTrenutniSlucajKoriscenja(SlucajKoriscenja.SK_OBRISI_PPN);
                String poruka = Controller.getInstance().obrisiPPN(ppn);
                JOptionPane.showMessageDialog(this, poruka);
                model.removePPN(row);
                TableStavkeModel stavkeModel = (TableStavkeModel) tblStavkePPN.getModel();
                stavkeModel.clearStavke();
            } catch (Exception ex) {
                Logger.getLogger(FormPretraziPPN.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(this, ex.getMessage());
            }
        } else {
            JOptionPane.showMessageDialog(this, "Izaberite plan.");
        }
    }//GEN-LAST:event_btnObrisiPPNActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormPretraziPPN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormPretraziPPN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormPretraziPPN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormPretraziPPN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormPretraziPPN().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIzmeniPPN;
    private javax.swing.JButton btnObrisiPPN;
    private javax.swing.JButton btnPrikaziPPN;
    private javax.swing.JButton btnPrikaziStavke;
    private javax.swing.JLabel jLblUlogovan;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblPlanovi;
    private javax.swing.JTable tblStavkePPN;
    // End of variables declaration//GEN-END:variables

    private void popuniTabeluPPN() {
        try {
            PlanoviTableModel model = new PlanoviTableModel(Controller.getInstance().getAllPPN());
            tblPlanovi.setModel(model);
        } catch (Exception ex) {
            Logger.getLogger(FormPretraziPPN.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void popuniTabeluStavke() {
        TableStavkeModel model = new TableStavkeModel();
        tblStavkePPN.setModel(model);
    }

    void updateData(PlanPokrivenostiNastave ppn) {
        PlanoviTableModel model = (PlanoviTableModel) tblPlanovi.getModel();
        model.updatePlanovi(ppn);
        TableStavkeModel modelStavke = (TableStavkeModel) tblStavkePPN.getModel();
        modelStavke.setData(ppn.getStavkePPN());
    }
}
