/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package form.nastavnik;

import controller.Controller;
import domain.Katedra;
import domain.Nastavnik;
import form.FormMode;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import session.Session;
import validator.Validator;

/**
 *
 * @author Korisnik
 */
public class DialogNoviNastavnik extends javax.swing.JDialog {

    /**
     * Creates new form DialogNoviNastavnik
     */
    public DialogNoviNastavnik(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
    }

    public DialogNoviNastavnik(java.awt.Frame aThis, boolean b, FormMode formMode) {
        super(aThis, b);
        initComponents();
        Nastavnik ulogovan = Session.getInstance().getUlogovan();
        jLblUlogovan.setText(ulogovan.toString());
        this.setLocationRelativeTo(null);
        populateCmbKatedra();
        postaviKomponente(formMode);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLblUlogovan = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblPass = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cmbKatedra = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtIme = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        txtPozicija = new javax.swing.JTextField();
        txtKabinet = new javax.swing.JTextField();
        txtKonsultacije = new javax.swing.JTextField();
        btnDodajNastavnika = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        txtPrezime = new javax.swing.JTextField();
        btnIzmeni = new javax.swing.JButton();
        btnPrikazi = new javax.swing.JButton();
        pswPassword = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Nastavnik"));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLblUlogovan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLblUlogovan, javax.swing.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Novi nastavnik"));

        jLabel1.setText("Ime:");

        jLabel2.setText("Email:");

        lblPass.setText("Sifra:");

        jLabel4.setText("Katedra:");

        cmbKatedra.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel5.setText("Pozicija:");

        jLabel6.setText("Kabinet:");

        jLabel7.setText("Konsultacije:");

        btnDodajNastavnika.setText("Dodaj");
        btnDodajNastavnika.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDodajNastavnikaActionPerformed(evt);
            }
        });

        jLabel8.setText("Prezime:");

        btnIzmeni.setText("Izmeni");
        btnIzmeni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIzmeniActionPerformed(evt);
            }
        });

        btnPrikazi.setText("OK");
        btnPrikazi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrikaziActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblPass, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtIme)
                            .addComponent(cmbKatedra, 0, 270, Short.MAX_VALUE)
                            .addComponent(txtEmail)
                            .addComponent(txtPozicija)
                            .addComponent(txtKabinet)
                            .addComponent(txtKonsultacije)
                            .addComponent(txtPrezime)
                            .addComponent(pswPassword)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnIzmeni, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDodajNastavnika, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnPrikazi, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtIme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtPrezime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPass)
                    .addComponent(pswPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cmbKatedra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtPozicija, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtKabinet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtKonsultacije, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDodajNastavnika)
                    .addComponent(btnIzmeni)
                    .addComponent(btnPrikazi))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDodajNastavnikaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDodajNastavnikaActionPerformed
        String ime = txtIme.getText().trim();
        String prezime = txtPrezime.getText().trim();
        String email = txtEmail.getText().trim();
        String sifra = new String(pswPassword.getPassword());
        Katedra katedra = (Katedra) cmbKatedra.getSelectedItem();
        String pozicija = txtPozicija.getText().trim();
        String kabinet = txtKabinet.getText().trim();
        String konsultacije = txtKonsultacije.getText().trim();
        Nastavnik nastavnik = new Nastavnik(-1, ime, prezime, email, sifra, pozicija, konsultacije, kabinet, katedra);
        if (Validator.getInstance().nastavnikOK(nastavnik)) {
            try {
                int id = Controller.getInstance().saveNastavnik(nastavnik);
                JOptionPane.showMessageDialog(this, "Nastavnik je sacuvan.");
                nastavnik.setNastavnikId(id);
                FormPretraziNastavnike fpn = new FormPretraziNastavnike();
                fpn.addNastavnik(nastavnik);
                this.dispose();
            } catch (Exception ex) {
                Logger.getLogger(DialogNoviNastavnik.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Podaci nisu dobro uneti.");
        }
    }//GEN-LAST:event_btnDodajNastavnikaActionPerformed

    private void btnPrikaziActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrikaziActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnPrikaziActionPerformed

    private void btnIzmeniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIzmeniActionPerformed
        Nastavnik izabran = (Nastavnik) Session.getInstance().getParametriSK().get("nastavnik");
        String ime = txtIme.getText().trim();
        String prezime = txtPrezime.getText().trim();
        String email = txtEmail.getText().trim();
        String password = izabran.getPassword();
        if (pswPassword.isVisible()) {
            password = new String(pswPassword.getPassword());
        }
        String konsultacije = txtKonsultacije.getText().trim();
        String kabinet = txtKabinet.getText().trim();
        Katedra katedra = (Katedra) cmbKatedra.getSelectedItem();
        String pozicija = txtPozicija.getText().trim();
        Nastavnik novi = new Nastavnik(izabran.getNastavnikId(), ime, prezime, email, password, pozicija, konsultacije, kabinet, katedra);
        if (Validator.getInstance().nastavnikOK(novi)) {
            try {
                String poruka = Controller.getInstance().azurirajNastavnika(novi);
                FormPretraziNastavnike fpn = (FormPretraziNastavnike) this.getParent();
                fpn.updateNastavnik(novi);
                JOptionPane.showMessageDialog(this, poruka);
                this.dispose();
            } catch (Exception ex) {
                Logger.getLogger(DialogNoviNastavnik.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(this, ex.getMessage());
            }
        } else {
            JOptionPane.showMessageDialog(this, "Podaci nisu dobro uneti.");
        }
    }//GEN-LAST:event_btnIzmeniActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DialogNoviNastavnik.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DialogNoviNastavnik.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DialogNoviNastavnik.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DialogNoviNastavnik.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DialogNoviNastavnik dialog = new DialogNoviNastavnik(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDodajNastavnika;
    private javax.swing.JButton btnIzmeni;
    private javax.swing.JButton btnPrikazi;
    private javax.swing.JComboBox cmbKatedra;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLblUlogovan;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblPass;
    private javax.swing.JPasswordField pswPassword;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtIme;
    private javax.swing.JTextField txtKabinet;
    private javax.swing.JTextField txtKonsultacije;
    private javax.swing.JTextField txtPozicija;
    private javax.swing.JTextField txtPrezime;
    // End of variables declaration//GEN-END:variables

    private void populateCmbKatedra() {
        try {
            cmbKatedra.removeAllItems();
            List<Katedra> katedre = Controller.getInstance().getAllKatedre();
            for (Katedra katedra : katedre) {
                cmbKatedra.addItem(katedra);
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
    }

    private void postaviKomponente(FormMode mode) {
        switch (mode) {
            case NOVI:
                btnIzmeni.setVisible(false);
                btnDodajNastavnika.setVisible(true);
                btnPrikazi.setVisible(false);
                setTitle("Novi nastavnik");
                break;
            case IZMENI:
                btnIzmeni.setVisible(true);
                btnDodajNastavnika.setVisible(false);
                btnPrikazi.setVisible(false);
                setSifra();
                setNastavnik();
                setTitle("Izmena nastavnika");
                break;
            case PRIKAZI:
                btnPrikazi.setVisible(true);
                btnIzmeni.setVisible(false);
                btnDodajNastavnika.setVisible(false);
                lblPass.setVisible(false);
                pswPassword.setVisible(false);
                disableFields();
                setNastavnik();
                setTitle("Prikaz nastavnika");
                break;
        }
    }

    private void setNastavnik() {
        if (!Session.getInstance().getParametriSK().isEmpty()) {
            Nastavnik nastavnik = (Nastavnik) Session.getInstance().getParametriSK().get("nastavnik");
            prikaziNastavnika(nastavnik);
        } else {
            JOptionPane.showMessageDialog(this, "Nastavnik nije izabran.");
        }
    }

    private void prikaziNastavnika(Nastavnik nastavnik) {
        txtIme.setText(nastavnik.getIme());
        txtPrezime.setText(nastavnik.getPrezime());
        txtEmail.setText(nastavnik.geteMail());
        pswPassword.setText(nastavnik.getPassword());
        cmbKatedra.setSelectedItem(nastavnik.getKatedra());
        txtPozicija.setText(nastavnik.getPozicija());
        txtKonsultacije.setText(nastavnik.getKonsultacije());
        txtKabinet.setText(nastavnik.getKabinet());
    }

    private void disableFields() {
        txtEmail.setEditable(false);
        txtIme.setEditable(false);
        txtKabinet.setEditable(false);
        txtKonsultacije.setEditable(false);
        txtPozicija.setEditable(false);
        txtPrezime.setEditable(false);
        cmbKatedra.setEnabled(false);
    }

    private void setSifra() {
        if (!Session.getInstance().getParametriSK().get("nastavnik").equals(Session.getInstance().getUlogovan())) {
            pswPassword.setVisible(false);
            lblPass.setVisible(false);
        }
    }
}
